# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Inputs'
on:
  workflow_dispatch:
    inputs:
      alphas:
        description: 'Miryoku Alphas'
        required: false
        default: 'qwerty'
      nav:
        description: 'Miryoku Nav'
        required: false
        default: 'default'
      clipboard:
        description: 'Miryoku Clipboard'
        required: false
        default: 'mac'
      layers:
        description: 'Miryoku Layers'
        required: false
        default: 'default'
      mapping:
        description: 'Miryoku Mapping'
        required: false
        default: 'default'
      kmonad_os:
        description: 'Miryoku KMonad 0S'
        required: false
        default: 'mac'
      rules:
        description: 'custom_rules.mk'
        required: false
        default: 'default'
      custom_config:
        description: 'custom_custom_config.h'
        required: false
        default: 'default'
jobs:
  process-inputs:
    runs-on: ubuntu-latest
    outputs:
      alphas: ${{ steps.process-inputs.outputs.alphas }}
      nav: ${{ steps.process-inputs.outputs.nav }}
      clipboard: ${{ steps.process-inputs.outputs.clipboard }}
      layers: ${{ steps.process-inputs.outputs.layers }}
      mapping: ${{ steps.process-inputs.outputs.mapping }}
      kmonad_os: ${{ steps.process-inputs.outputs.kmonad_os }}
      rules: ${{ steps.process-inputs.outputs.rules }}
      custom_config: ${{ steps.process-inputs.outputs.custom_config }}
    steps:
      - name: Process inputs
        id: process-inputs
        run: |
          set-output()
          {
            json=`echo "$2" | jq -cnR 'inputs | split(",";"")'`
            echo "$1=$json" >> $GITHUB_OUTPUT
          }
          set-output "alphas" "${{ github.event.inputs.alphas }}"
          set-output "nav" "${{ github.event.inputs.nav }}"
          set-output "clipboard" "${{ github.event.inputs.clipboard }}"
          set-output "layers" "${{ github.event.inputs.layers }}"
          set-output "mapping" "${{ github.event.inputs.mapping }}"
          set-output "kmonad_os" "${{ github.event.inputs.kmonad_os }}"
          set-output "rules" "${{ github.event.inputs.rules }}"
          set-output "custom_config" "${{ github.event.inputs.custom_config }}"
  build:
    uses: ./.github/workflows/main.yml
    needs: process-inputs
    with:
      mode: '["build"]'
      alphas: ${{ needs.process-inputs.outputs.alphas }}
      nav: ${{ needs.process-inputs.outputs.nav }}
      clipboard: ${{ needs.process-inputs.outputs.clipboard }}
      layers: ${{ needs.process-inputs.outputs.layers }}
      mapping: ${{ needs.process-inputs.outputs.mapping }}
      kmonad_os: ${{ needs.process-inputs.outputs.kmonad_os }}
      rules: ${{ needs.process-inputs.outputs.rules }}
      custom_config: ${{ needs.process-inputs.outputs.custom_config }}
